---
- name: Apache Server Installed
  hosts: AppServers
  become: true 
  tasks:
    - name: Latest Apache Version Installed
      yum:
        name: httpd
        state: latest
    - name: Apache enabled and running
      service:
        name: httpd
        enabled: true
        state: started
